(require "ID44" "id44.lisp")

(provide "ZOS-PATH")

(defun zos_path-recognize (l)
  (cond ((stringp l) (zos_path-recognize (coerce l 'list)))
        ((listp l) (let ((id44 (id44-recognize l))) 
                     (if (= (length id44) 3) 
                         (list (if (null (second (car id44)))
                                   (car (car id44))
                                 (append (car (car id44))
                                         (list #\()
                                         (second (car id44))
                                         (list #\)))) 
                               (second id44)
                               (third id44)) 
                       NIL)))
  )
)

